openapi: "3.0.1"
info:
  title: "Basic"
  contact:
    name: OpenAPI Generator
    email: caizhenghai@gmail.com
  description: >-
    ### Error Code

    this is response body code if error occurs.

    - 42000: invalid argument error

    - 50000: internal error

  version: 1.0.0
servers:
  - url: https://localhost:8080/api/v1
    description: Live Server
  - url: https://localhost:8080/api
    description: Only for health check
